LANGUAGE_SUPPORT_LIBRARY = {'ar': 'pysbd',
'arb': 'pysbd',
'ben': 'bltk',
'bn': 'bltk',
'en': 'nltk',
'eng': 'nltk',
'es': 'pysbd',
'fa': 'pysbd',
'fr': 'pysbd',
'fra': 'pysbd',
'gu': 'indic',
'guj': 'indic',
'hi': 'indic',
'hin': 'indic',
'id': 'spacy',
'ind': 'spacy',
'mar': 'indic',
'mr': 'indic',
'ne': 'spacy',
'npi': 'spacy',
'pa': 'indic',
'pan': 'indic',
'pes': 'pysbd',
'por': 'nltk',
'pt': 'nltk',
'ru': 'pysbd',
'rus': 'pysbd',
'spa': 'pysbd',
'ta': 'indic',
'tam': 'indic',
'te': 'indic',
'tel': 'indic',
'tr': 'nltk',
'tur': 'nltk',
'uk': 'spacy',
'ukr': 'spacy',
'ur': 'pysbd',
'urd': 'pysbd',
'zh': 'spacy',
'zho': 'spacy',
'am': 'pysbd',
'hy': 'pysbd',
'bg': 'pysbd',
'pl': 'pysbd',
'nl': 'pysbd',
'da': 'pysbd',
'my': 'pysbd',
'el': 'pysbd',
'it': 'pysbd',
'ja': 'pysbd',
'de': 'pysbd',
'kk': 'pysbd',
'sk': 'pysbd',
'yo':'spacy',
'vi':'spacy',
'th':'spacy',
'sl':'spacy',
'si':'spacy',
'or':'indic',
'kn':'indic',
'ml':'indic',
'si':'indic',
'kk':'indic',
'or':'indic',
}

def get_support_library(language:str):
    try:
        return LANGUAGE_SUPPORT_LIBRARY[language]
    except KeyError:
        raise ValueError("Provide valid language ID i.e. ISO code. "
            "Available codes are : {}".format(set([key for key in LANGUAGE_SUPPORT_LIBRARY.keys() if len(key)<3])))